/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125472-g97cbffe917-20260705"
#endif /* AVUTIL_FFVERSION_H */
